# buildah build -f Dockerfile.2048.rhel9.v1 -t 2048-connect:v2
# podman run --rm -d -p 8080:8081 localhost/2048-connect:v2
FROM registry.redhat.io/rhel9/nginx-120
MAINTAINER ---YOUR NAME--- <YOUR EM@IL>
COPY files/src /opt/app-root/src
COPY files/logo.png /opt/app-root/src/logo.png
COPY files/nginx.conf /etc/nginx/nginx.conf
EXPOSE 8081
ENTRYPOINT ["nginx", "-g", "daemon off;"]
