---
builder_blueprint_name: prod-{{ gitea_user_name }}{{ user_number }}
builder_request_timeout: 600
builder_wait_compose_timeout: 2400
builder_compose_type: edge-commit
builder_skip_repo: true
builder_compose_pkgs:
  - libreswan
  - microshift
  - microshift-olm
  - wait-microshift
  - firewalld
  - openshift-clients
  - podman
  - vim-enhanced
  - NetworkManager-wifi
  - "fuse-overlayfs"
  - "setroubleshoot-server"
  - "slirp4netns"
  - "net-tools"
  - cockpit
  - cockpit-machines
  - cockpit-podman
  - cockpit-system
  - cockpit-bridge
  - cockpit-pcp
  - cockpit-storaged
  - cockpit-session-recording
  - libvirt-daemon-config-network
  - libvirt-daemon-kvm
  - qemu-kvm
  - qemu-img
  - virt-install
  - libguestfs-tools
  - python3-libguestfs
  - virt-top
  - "git"
  - inotify-gitops
  - workload-manifests
  - tcpdump
builder_compose_customizations:
  user:
    name: "{{ rhde_user_name }}"
    description: "Admin user"{% raw %}
    #password: "$6$3C0fNaU.aqxvP2wf$WaH5Us4KVqsEMFzXrwLqI8l0UekVvzPUEaFwqeN0BPZ3ZJDN4E7qlsXL48R9rVIdoM2q/HMOiurhHXQ9JiFV11"
    {% endraw %}password: "{{ rhde_user_password }}"
    groups: ["users", "wheel"]
  services:
    enabled: ["microshift", "cockpit.socket"]
  firewall:
    ports: ["22:tcp", "80:tcp", "443:tcp", "6443:tcp", "5353:udp", "30000-32767:tcp", "30000-32767:udp", "9090:tcp"]

